# Generated by Django 5.0.1 on 2024-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_owner', models.CharField(max_length=50)),
                ('Pet_type', models.CharField(max_length=50)),
                ('No_pets', models.IntegerField()),
                ('Breed', models.CharField(max_length=50)),
                ('Service', models.CharField(max_length=50)),
                ('Date_of_service', models.DateField()),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Photo', models.FileField(upload_to='')),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Licence', models.FileField(upload_to='')),
                ('Username', models.CharField(max_length=50)),
                ('Action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Service', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=50)),
            ],
        ),
    ]
