# Generated by Django 5.0.1 on 2024-02-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_owner', models.CharField(max_length=50)),
                ('Pet_caretaker', models.CharField(max_length=50)),
                ('Msg_type', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
            ],
        ),
    ]
