# Generated by Django 5.0.1 on 2024-03-11 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0003_booking_pstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='adpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='p_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_owner', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Email', models.EmailField(max_length=254)),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
