# Generated by Django 5.0.1 on 2024-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0006_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Ct',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
